# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('a_amount', models.IntegerField(max_length=20)),
                ('a_score', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('h_amount', models.IntegerField(max_length=20)),
                ('h_score', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('l_amount', models.IntegerField(max_length=20)),
                ('l_score', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('m_amount', models.IntegerField(max_length=20)),
                ('m_score', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stolen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30)),
                ('s_amount', models.IntegerField(max_length=20)),
                ('s_score', models.IntegerField(max_length=5)),
            ],
        ),
    ]
