# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='a_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accident',
            name='a_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='h_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='h_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='library',
            name='l_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='library',
            name='l_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='m_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='m_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stolen',
            name='s_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stolen',
            name='s_score',
            field=models.IntegerField(),
        ),
    ]
