# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='m_fk',
            new_name='h_fk',
        ),
    ]
